# Generated by Claude Code on 2025-12-12

from django.db import migrations, transaction

import logging
logger = logging.getLogger("plane.migrations")

BATCH_SIZE = 1000


def create_default_issue_types(apps, schema_editor):
    """
    Create default issue types for all existing projects.

    Creates a "Task" issue type at the workspace level if it doesn't exist,
    then associates it with all projects in that workspace.
    """
    Project = apps.get_model("db", "Project")
    IssueType = apps.get_model("db", "IssueType")
    ProjectIssueType = apps.get_model("db", "ProjectIssueType")
    Issue = apps.get_model("db", "Issue")

    # Get all workspaces with their projects
    from django.db.models import Count
    workspaces = (
        Project.objects.values("workspace_id")
        .annotate(project_count=Count("id"))
        .order_by("workspace_id")
    )

    total_workspaces = len(workspaces)
    logger.info(f"Processing {total_workspaces} workspaces for default issue types...")

    for idx, workspace_data in enumerate(workspaces, 1):
        workspace_id = workspace_data["workspace_id"]

        try:
            with transaction.atomic():
                # Create or get default "Task" issue type for this workspace
                task_type, created = IssueType.objects.get_or_create(
                    workspace_id=workspace_id,
                    name="Task",
                    defaults={
                        "description": "Default work item type with the option to add new properties",
                        "is_default": True,
                        "is_active": True,
                        "is_epic": False,
                        "level": 0,
                        "logo_props": {
                            "icon": "task",
                            "color": "#3b82f6"
                        },
                    },
                )

                if created:
                    logger.info(f"[{idx}/{total_workspaces}] Created default Task type for workspace {workspace_id}")
                else:
                    logger.info(f"[{idx}/{total_workspaces}] Task type already exists for workspace {workspace_id}")

                # Get all projects in this workspace
                projects = Project.objects.filter(workspace_id=workspace_id)
                projects_count = projects.count()

                # Associate the Task type with all projects in the workspace
                project_types_to_create = []
                issues_to_update = []

                for project in projects:
                    # Check if association already exists
                    if not ProjectIssueType.objects.filter(
                        project=project,
                        issue_type=task_type
                    ).exists():
                        project_types_to_create.append(
                            ProjectIssueType(
                                project=project,
                                issue_type=task_type,
                                is_default=True,
                                level=0,
                            )
                        )

                    # Find issues in this project without a type
                    project_issues = Issue.objects.filter(
                        project=project,
                        type__isnull=True
                    )

                    for issue in project_issues:
                        issue.type = task_type
                        issues_to_update.append(issue)

                # Bulk create project-issue type associations
                if project_types_to_create:
                    ProjectIssueType.objects.bulk_create(
                        project_types_to_create,
                        batch_size=BATCH_SIZE,
                        ignore_conflicts=True,
                    )
                    logger.info(
                        f"  ↳ Associated Task type with {len(project_types_to_create)} projects"
                    )

                # Bulk update issues to have the default type
                if issues_to_update:
                    Issue.objects.bulk_update(
                        issues_to_update,
                        ["type"],
                        batch_size=BATCH_SIZE,
                    )
                    logger.info(
                        f"  ↳ Updated {len(issues_to_update)} issues to use Task type"
                    )

        except Exception as e:
            logger.error(
                f"Error processing workspace {workspace_id}: {str(e)}"
            )
            # Continue with next workspace instead of failing the entire migration
            continue

    logger.info("✅ Default issue types migration completed")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by removing auto-created issue types.

    Note: This only removes issue types that were created by this migration
    (i.e., Task types that are marked as default).
    """
    IssueType = apps.get_model("db", "IssueType")
    ProjectIssueType = apps.get_model("db", "ProjectIssueType")

    # Delete project associations
    deleted_associations = ProjectIssueType.objects.filter(
        issue_type__name="Task",
        issue_type__is_default=True,
        is_default=True,
    ).delete()

    logger.info(f"Deleted {deleted_associations[0]} project-issue type associations")

    # Delete the issue types
    deleted_types = IssueType.objects.filter(
        name="Task",
        is_default=True,
    ).delete()

    logger.info(f"Deleted {deleted_types[0]} default Task issue types")


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0112_auto_20251124_0603"),
    ]

    operations = [
        migrations.RunPython(
            create_default_issue_types,
            reverse_code=reverse_migration,
        ),
    ]
