# Generated by Django manually

from django.db import migrations
import uuid


def create_default_issue_types(apps, schema_editor):
    """Create default issue types for all existing workspaces."""
    IssueType = apps.get_model("db", "IssueType")
    Workspace = apps.get_model("db", "Workspace")

    default_types = [
        {
            "name": "Requirement",
            "description": "A requirement or specification for the product",
            "logo_props": {"in_use": "icon", "icon": {"name": "file-text", "color": "#3b82f6"}},
            "is_default": True,
            "is_active": True,
            "level": 0,
        },
        {
            "name": "Story",
            "description": "A user story describing a feature from the user's perspective",
            "logo_props": {"in_use": "icon", "icon": {"name": "book-open", "color": "#10b981"}},
            "is_default": False,
            "is_active": True,
            "level": 1,
        },
        {
            "name": "Bug",
            "description": "A defect or issue that needs to be fixed",
            "logo_props": {"in_use": "icon", "icon": {"name": "bug", "color": "#ef4444"}},
            "is_default": False,
            "is_active": True,
            "level": 2,
        },
    ]

    # Get all workspaces
    workspaces = Workspace.objects.all()

    for workspace in workspaces:
        # Check if workspace already has issue types
        existing_types = IssueType.objects.filter(workspace=workspace).count()
        if existing_types > 0:
            continue

        # Create default issue types for this workspace
        for type_data in default_types:
            IssueType.objects.create(
                id=uuid.uuid4(),
                workspace=workspace,
                **type_data
            )


def reverse_create_default_issue_types(apps, schema_editor):
    """Remove default issue types created by this migration."""
    IssueType = apps.get_model("db", "IssueType")
    # Only delete issue types with the specific default names
    IssueType.objects.filter(name__in=["Requirement", "Story", "Bug"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0117_rename_description_draftissue_description_json_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_default_issue_types,
            reverse_code=reverse_create_default_issue_types,
        ),
    ]
