# Generated by Django manually

from django.db import migrations
import uuid


def add_task_issue_type(apps, schema_editor):
    """Add Task issue type and set it as default."""
    IssueType = apps.get_model("db", "IssueType")
    Workspace = apps.get_model("db", "Workspace")

    # Get all workspaces
    workspaces = Workspace.objects.all()

    for workspace in workspaces:
        # Set Requirement to non-default
        IssueType.objects.filter(
            workspace=workspace,
            name="Requirement",
            is_default=True
        ).update(is_default=False)

        # Check if Task type already exists
        if IssueType.objects.filter(workspace=workspace, name="Task").exists():
            # Just set it as default if it exists
            IssueType.objects.filter(workspace=workspace, name="Task").update(is_default=True)
            continue

        # Create Task type as default
        IssueType.objects.create(
            id=uuid.uuid4(),
            workspace=workspace,
            name="Task",
            description="A task or action item to be completed",
            logo_props={
                "in_use": "icon",
                "icon": {"name": "circle-check", "color": "#6b7280"}
            },
            is_default=True,
            is_active=True,
            level=-1,  # Place before Requirement
        )


def reverse_add_task_issue_type(apps, schema_editor):
    """Remove Task type and restore Requirement as default."""
    IssueType = apps.get_model("db", "IssueType")
    Workspace = apps.get_model("db", "Workspace")

    workspaces = Workspace.objects.all()

    for workspace in workspaces:
        # Delete Task type
        IssueType.objects.filter(workspace=workspace, name="Task").delete()

        # Restore Requirement as default
        IssueType.objects.filter(
            workspace=workspace,
            name="Requirement"
        ).update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0118_seed_default_issue_types"),
    ]

    operations = [
        migrations.RunPython(
            add_task_issue_type,
            reverse_code=reverse_add_task_issue_type,
        ),
    ]
