# Generated by Django manually

from django.db import migrations


def initialize_project_task_types(apps, schema_editor):
    """Initialize Task type for existing projects that have no ProjectIssueType."""
    Project = apps.get_model("db", "Project")
    IssueType = apps.get_model("db", "IssueType")
    ProjectIssueType = apps.get_model("db", "ProjectIssueType")

    # Find projects without any ProjectIssueType
    projects_without_types = Project.objects.exclude(
        id__in=ProjectIssueType.objects.values_list("project_id", flat=True)
    ).select_related("workspace")

    project_issue_types_to_create = []
    for project in projects_without_types:
        # Try to find Task type for the workspace
        issue_type = IssueType.objects.filter(
            workspace=project.workspace,
            name="Task",
            is_active=True,
        ).first()

        # Fall back to workspace default type
        if not issue_type:
            issue_type = IssueType.objects.filter(
                workspace=project.workspace,
                is_default=True,
                is_active=True,
            ).first()

        # Fall back to any active type
        if not issue_type:
            issue_type = IssueType.objects.filter(
                workspace=project.workspace,
                is_active=True,
            ).first()

        if issue_type:
            project_issue_types_to_create.append(
                ProjectIssueType(
                    workspace=project.workspace,
                    project=project,
                    issue_type=issue_type,
                    is_default=True,
                    level=0,
                )
            )

    if project_issue_types_to_create:
        ProjectIssueType.objects.bulk_create(project_issue_types_to_create, batch_size=100)


def reverse_initialize(apps, schema_editor):
    """No reverse needed - removing types is handled by the settings UI."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0119_add_task_issue_type"),
    ]

    operations = [
        migrations.RunPython(
            initialize_project_task_types,
            reverse_code=reverse_initialize,
        ),
    ]
