# Generated by Django 4.2.27 on 2026-02-05 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0120_initialize_project_task_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='extra_properties',
            field=models.JSONField(blank=True, default=dict, help_text='Additional properties based on issue type configuration'),
        ),
        migrations.CreateModel(
            name='ExtraPropertyConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(help_text='Unique identifier for the property within an issue type', max_length=100)),
                ('label', models.CharField(help_text='Display name for the property', max_length=255)),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('select', 'Select'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('markdown', 'Markdown')], help_text='Type of input control', max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description/help text')),
                ('required', models.BooleanField(default=False, help_text='Whether this property is required')),
                ('sort_order', models.FloatField(default=65535, help_text='Order of the property in the form')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Type-specific configuration')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_property_configs', to='db.issuetype')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_property_configs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Extra Property Config',
                'verbose_name_plural': 'Extra Property Configs',
                'db_table': 'extra_property_configs',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='extrapropertyconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue_type', 'key'), name='extra_property_config_unique_issue_type_key_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='extrapropertyconfig',
            unique_together={('issue_type', 'key', 'deleted_at')},
        ),
    ]
