# Generated by Django 4.2.27 on 2026-02-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_move_required_to_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuserproperty',
            name='extra_display_properties',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='extrapropertyconfig',
            name='key',
            field=models.CharField(help_text='Unique identifier for the property within a workspace', max_length=100),
        ),
    ]
