# Generated by Django 4.2.27 on 2026-02-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_add_extra_display_properties_to_project_user_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueview',
            name='extra_display_properties',
            field=models.JSONField(default=dict),
        ),
    ]
