# Generated by Django manually

from django.db import migrations
import uuid


def create_milestone_report_issue_types(apps, schema_editor):
    """Create Milestone and Report issue types for all existing workspaces."""
    IssueType = apps.get_model("db", "IssueType")
    Workspace = apps.get_model("db", "Workspace")

    new_types = [
        {
            "name": "Milestone",
            "description": "A milestone marking a key delivery stage within a project",
            "logo_props": {"in_use": "icon", "icon": {"name": "flag", "color": "#f59e0b"}},
            "is_default": False,
            "is_active": True,
            "level": 3,
        },
        {
            "name": "Report",
            "description": "A progress report or stage summary for a project",
            "logo_props": {"in_use": "icon", "icon": {"name": "file-chart", "color": "#8b5cf6"}},
            "is_default": False,
            "is_active": True,
            "level": 4,
        },
    ]

    workspaces = Workspace.objects.all()

    for workspace in workspaces:
        for type_data in new_types:
            # Idempotent: skip if already exists
            if IssueType.objects.filter(workspace=workspace, name=type_data["name"]).exists():
                continue
            IssueType.objects.create(
                id=uuid.uuid4(),
                workspace=workspace,
                **type_data,
            )


def reverse_create_milestone_report_issue_types(apps, schema_editor):
    """Remove Milestone and Report issue types created by this migration."""
    IssueType = apps.get_model("db", "IssueType")
    IssueType.objects.filter(name__in=["Milestone", "Report"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0126_add_employee_fields"),
    ]

    operations = [
        migrations.RunPython(
            create_milestone_report_issue_types,
            reverse_code=reverse_create_milestone_report_issue_types,
        ),
    ]
